// react-client/src/CatelogList.js
import { ItemVariationList } from "./ItemVariationList";

const CatelogList = ({ objects, onItemClick }) => {
  return objects?.length > 0
    ? objects.map((object) => {
        const { item_data, id } = object;

        return (
          <div className="list-item" key={id}>
            <div className="name">{item_data.name}</div>
            <div>{item_data.description}</div>
            <br />
            <ItemVariationList
              variations={item_data.variations}
              onItemClick={onItemClick}
            />
          </div>
        );
      })
    : "No items found";
};

export { CatelogList };

// svelte-client/src/CatelogList.svelte
<script>
  import ItemVariationList from "./ItemVariationList.svelte";
  export let items = [];
  export let onItemClicked = () => {};
</script>

{#each items as item}
  <div class="list-item">
    <div class="name">{item.item_data.name}</div>
    <div>{item.item_data.description}</div>
    <br />
    <ItemVariationList {onItemClicked} variations={item.item_data.variations} />
  </div>
{/each}
